In [1]:
l = [2345, 27, 546, 215, -1234]

In [2]:
l

[2345, 27, 546, 215, -1234]

In [1]:
import numpy as np

In [5]:
a = np.array(l)

In [6]:
a

array([ 2345,    27,   546,   215, -1234])

In [7]:
b = np.array([12,455, 63.3, True, 'abc'])

In [8]:
b

array(['12', '455', '63.3', 'True', 'abc'], dtype='<U32')

In [9]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [10]:
#different than a list , array have just one type of elements, like a Vector in R

In [13]:
l.pop()

-1234

In [14]:
l

[2345, 27, 546, 215]

In [15]:
a.mean()

379.8

---- #Slicing Arrays ---

In [16]:
a

array([ 2345,    27,   546,   215, -1234])

In [17]:
a[2:]

array([  546,   215, -1234])

In [18]:
a[2:4]

array([546, 215])

In [19]:
# slice a list you creat a copy but in slicig an array no, you are creating a view, a new view of the array, so pay attention

In [21]:
a[2:4]

array([546, 215])

In [22]:
b = a[2:4]

In [23]:
b

array([546, 215])

In [24]:
b[0]

546

In [25]:
b[:]

array([546, 215])

In [26]:
b[:] = 111

In [27]:
b

array([111, 111])

In [28]:
a

array([ 2345,    27,   111,   111, -1234])

In [29]:
#look, when you define b as 111, this replace the [2:4] element of a

In [32]:
# to copy an array, making more save

c = a.copy()

In [33]:
c

array([ 2345,    27,   111,   111, -1234])